import os
import sys

# add building.py path
sys.path = sys.path + [os.path.join('..','..','..','tools')]
from building import *

BuildApplication('imx6ull_drv_enet', 'SConscript', usr_root = '../../')
