from building import *

cwd = GetCurrentDir()
src = Glob('src/*.c') + Glob('src/*.cpp') + Glob('cmd_channel/*.c') + Glob('cmd_channel/*.cpp') + Glob('netdev/*.c') + Glob('netdev/*.cpp') + Glob('usocket/*.c') + Glob('dfs/*.c')
CPPPATH = [cwd, cwd + '/src', cwd + '/cmd_channel', cwd + '/netdev', cwd + '/usocket', cwd + '/dfs']

CPPDEFINES = [
        'RT_USING_NEWLIB',
        'HAVE_CCONFIG_H',
]

group = DefineGroup('lwIPKit', src, depend = ['RT_USING_LWIP', 'SAL_USING_UNET'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

if GetDepend(['RT_USING_LWIP212']):
    lwipdir = 'lwip-2.1.2'
    path = os.path.join(cwd, lwipdir)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        group = group + SConscript(os.path.join(lwipdir, 'SConscript'))

if GetDepend(['RT_USING_LWIP202']):
    lwipdir = 'lwip-2.0.2'
    path = os.path.join(cwd, lwipdir)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        group = group + SConscript(os.path.join(lwipdir, 'SConscript'))

group = group + SConscript(os.path.join("drv_enet", 'SConscript')) + SConscript(os.path.join("QUA_var", 'SConscript'))

Return('group')
